#!/bin/sh
# This file MUST be run from to tools/requirements directory.

autogen_message="# THIS IS AN AUTOGENERATED FILE, DO NOT MODIFY.\n# SEE CONTRIBUTING.md FOR INSTRUCTIONS ON UPDATING REQUIREMENTS"

# CPU (non-dev)
generated_file=../../cpu_requirements.txt
echo $autogen_message > $generated_file
tail -n +2 cpu_only_requirements.txt >> $generated_file
echo "" >> $generated_file
tail -n +2 shared_requirements.txt >> $generated_file

# CPU (dev)
generated_file=../../cpu_dev_requirements.txt
echo $autogen_message > $generated_file
tail -n +2 cpu_only_requirements.txt >> $generated_file
echo "" >> $generated_file
tail -n +2 shared_requirements.txt >> $generated_file
echo "" >> $generated_file
tail -n +2 dev_requirements.txt >> $generated_file

# CUDA (non-dev)
generated_file=../../cuda_requirements.txt
echo $autogen_message > $generated_file
tail -n +2 cuda_only_requirements.txt >> $generated_file
echo "" >> $generated_file
tail -n +2 shared_requirements.txt >> $generated_file

# CUDA (dev)
generated_file=../../cuda_dev_requirements.txt
echo $autogen_message > $generated_file
tail -n +2 cuda_only_requirements.txt >> $generated_file
echo "" >> $generated_file
tail -n +2 shared_requirements.txt >> $generated_file
echo "" >> $generated_file
tail -n +2 dev_requirements.txt >> $generated_file
